default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: guestbook_development
  username: postgres

test:
  <<: *default
  database: guestbook_test
  username: postgres

production:
  <<: *default
  database: guestbook_production
  username: postgres